# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = textserver
QT+=network
DESTDIR = ./x64/Debug
CONFIG += debug console
DEFINES += _CONSOLE _UNICODE _ENABLE_EXTENDED_ALIGNED_STORAGE WIN64 _UNICODE _ENABLE_EXTENDED_ALIGNED_STORAGE WIN64
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles
OBJECTS_DIR += debug
UI_DIR += GeneratedFiles
RCC_DIR += GeneratedFiles
include(textserver.pri)
